name: Core Banking Database
contact: yulei@hashicorp.com
enviroment: production
business_unit: retail_banking
aws_auth_role: corebanking-database
pki: corebanking-database.machine-id.customer.demo
identity_policies:
  - corebanking