name: vault_config_as_code_aws
contact: yulei@hashicorp.com
enviroment: development
business_unit: demo
aws_auth_role: 
pki: 
github_repo: 
tfc_workspace: "organization:yulei:project:Development:workspace:vault-config-as-code-aws"
identity_policies:
  - application-identity-token-policies
  - super-user