name: Core Banking Backend
contact: yulei@hashicorp.com
enviroment: production
business_unit: retail_banking
aws_auth_role: corebanking-backend
pki: corebanking-backend.machine-id.customer.demo
github_repo: 
tfc_workspace:
identity_policies:
  - application-identity-token-policies